# This workflow commits whenever a version of wine-appimage stable is released
# https://stackoverflow.com/questions/58465057/trigger-a-github-action-when-another-repository-creates-a-new-release
# Thanks to peterevans
name: WINE_AppImage_versioncheck
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
  
jobs:
  get-release-ver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/mmtrt/WINE_AppImage/releases/tags/continuous-stable | \
          jq -r ".assets[0].browser_download_url" > wine-appimage-versions/wine-appimage-stable-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'actionman'
          git config --global user.email 'keyserUS@users.noreply.github.com'
          git commit -am "[ACTION] New wine release version"
          git push
